### ISSUE TITLE
Launcher icons

### ISSUE THREAD

**Issue by seemir** [seemir/mydrive#24]
**Launcher icons:**

- [x] Update launcher icons to use the same icons as before migration to `flutter.io`
- [x] Add standard myDrive icon to "assets/icons" foler
- [x] Update `pubspec.yaml` with dependency to `flutter_launcher_icons v.0.8.1` and point to standard icon defined above with

```
flutter_icons:
  image_path: "assets/icons/launch.jpg"
  android: true
  ios: true

flutter_launcher_name:
  name: "myDrive"
```
